### ISSUE TITLE
Java Heap Space exception

### ISSUE THREAD

**Issue by owenmartin-toast** [jfrog/gradle-dep-tree#17]
### Describe the bug

I am using this plugin via the JFrog CLI, but I receive a `Java Heap space` exception;

The init script is as follows;
```
initscript {
    repositories { 
		mavenCentral()
    }
    dependencies {
        classpath 'com.jfrog:gradle-dep-tree:2.2.0'
    }
}
```

So I am using the latest version. 

I have the following in my `gradle.properties` file in my repository
```org.gradle.jvmargs=-Xmx4096M```

### Current behavior

```
Exception in thread "Daemon client event forwarder" java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.addConditionWaiter(AbstractQueuedSynchronizer.java:1896)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2114)
        at java.base/java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:458)
        at org.gradle.launcher.daemon.server.exec.DaemonConnectionBackedEventConsumer$ForwardEvents.getNextEvent(DaemonConnectionBackedEventConsumer.java:72)
        at org.gradle.launcher.daemon.server.exec.DaemonConnectionBackedEventConsumer$ForwardEvents.run(DaemonConnectionBackedEventConsumer.java:59)

```

### Gradle Dependency Tree version

2.2.0

### Operating system type and version

MacOS Ventura

**Comment by asafgabai** [comment]
Hi @owenmartin-toast, the fix for the high memory consumption has been implemented and is now part of version 3.0.0.
Please note that the output structure of the plugin has been changed.
Please let us know if you encounter any further issues or have any additional feedback.

**Comment by owenmartin-toast** [comment]
Hi,

I can confirm this fixes the issue, thank you!

Owen
